In [1]:
import numpy as np

In [3]:
# 1-dimensional array

arr_1 = np.array([11,12,13])
print(arr_1)
arr_1

[11 12 13]


array([11, 12, 13])

In [4]:
# 2-dimensional array

arr_2 = np.array([[11,12,13],[1,2,3]])
print(arr_2)
arr_2

[[11 12 13]
 [ 1  2  3]]


array([[11, 12, 13],
       [ 1,  2,  3]])

In [7]:
# Shape of array

print(arr_2.shape)    #2D array, "shape" object gives number of rows and columns of array

(2, 3)


In [9]:
# "ndim" object given the dimensional of array

print(arr_1.ndim)
print(arr_2.ndim)

1
2


In [11]:
# Creating the array using arange function

arr_3 = np.arange(5)
print(arr_3)

arr_31 = np.arange(5,10)
print(arr_31)

arr_32 = np.arange(5,30,5)
print(arr_32)

[0 1 2 3 4]
[5 6 7 8 9]
[ 5 10 15 20 25]


In [13]:
arr_4 = np.arange(9,13)
arr_4

array([ 9, 10, 11, 12])

In [15]:
#creating array using "np.linspace" function

arr_4 = np.linspace(0,1,10)
print(arr_4)
arr_4

[0.         0.11111111 0.22222222 0.33333333 0.44444444 0.55555556
 0.66666667 0.77777778 0.88888889 1.        ]


array([0.        , 0.11111111, 0.22222222, 0.33333333, 0.44444444,
       0.55555556, 0.66666667, 0.77777778, 0.88888889, 1.        ])

In [17]:
# Using "np.ones" function

arr_5 = np.ones((2,3))
print(arr_5)
arr_5

[[1. 1. 1.]
 [1. 1. 1.]]


array([[1., 1., 1.],
       [1., 1., 1.]])

In [20]:
# Using "np.zeros" function

arr_6 = np.zeros((5,3))
arr_6

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [25]:
a = np.zeros((5,10000000000))
a

MemoryError: 

In [22]:
# Using "np.eye" function

arr_7 = np.eye(4)
arr_7    #identical matrix of 4x4

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [23]:
# Using "np.diag" function

arr_8 = np.diag((1,2,3,4))
arr_8

array([[1, 0, 0, 0],
       [0, 2, 0, 0],
       [0, 0, 3, 0],
       [0, 0, 0, 4]])

In [28]:
# Using "np.random" function

arr_9 = np.random.rand(4)  # 1D array
print(arr_9)

print("\n")

arr_91 = np.random.rand(4,2)  #2D array
print(arr_91)

[0.23173361 0.95749353 0.91560277 0.73310862]


[[0.85962216 0.92602411]
 [0.02041012 0.48533032]
 [0.01407045 0.88615663]
 [0.04709112 0.61902318]]


In [29]:
arr_10 = np.random.randn(5)
arr_10

array([-1.70952215,  0.13149748,  0.18742687,  0.29181628, -0.51499172])

In [30]:
dir(np.random)

['Lock',
 'RandomState',
 '__RandomState_ctor',
 '__all__',
 '__builtins__',
 '__cached__',
 '__doc__',
 '__file__',
 '__loader__',
 '__name__',
 '__package__',
 '__path__',
 '__spec__',
 'absolute_import',
 'beta',
 'binomial',
 'bytes',
 'chisquare',
 'choice',
 'dirichlet',
 'division',
 'exponential',
 'f',
 'gamma',
 'geometric',
 'get_state',
 'gumbel',
 'hypergeometric',
 'info',
 'laplace',
 'logistic',
 'lognormal',
 'logseries',
 'mtrand',
 'multinomial',
 'multivariate_normal',
 'negative_binomial',
 'noncentral_chisquare',
 'noncentral_f',
 'normal',
 'np',
 'operator',
 'pareto',
 'permutation',
 'poisson',
 'power',
 'print_function',
 'rand',
 'randint',
 'randn',
 'random',
 'random_integers',
 'random_sample',
 'ranf',
 'rayleigh',
 'sample',
 'seed',
 'set_state',
 'shuffle',
 'standard_cauchy',
 'standard_exponential',
 'standard_gamma',
 'standard_normal',
 'standard_t',
 'test',
 'triangular',
 'uniform',
 'vonmises',
 'wald',
 'warnings',
 'weibull',
 'zipf']

In [3]:
# Using "np.empty" function

arr_10 = np.empty((4,3))
arr_10

array([[4.45057637e-308, 1.78021527e-306, 8.45549797e-307],
       [1.37962049e-306, 1.11260619e-306, 1.78010255e-306],
       [9.79054228e-307, 4.45057637e-308, 8.45596650e-307],
       [9.34602321e-307, 4.94065646e-322, 1.42410974e-306]])

In [4]:
help(np.empty)

Help on built-in function empty in module numpy.core.multiarray:

empty(...)
    empty(shape, dtype=float, order='C')
    
    Return a new array of given shape and type, without initializing entries.
    
    Parameters
    ----------
    shape : int or tuple of int
        Shape of the empty array, e.g., ``(2, 3)`` or ``2``.
    dtype : data-type, optional
        Desired output data-type for the array, e.g, `numpy.int8`. Default is
        `numpy.float64`.
    order : {'C', 'F'}, optional, default: 'C'
        Whether to store multi-dimensional data in row-major
        (C-style) or column-major (Fortran-style) order in
        memory.
    
    Returns
    -------
    out : ndarray
        Array of uninitialized (arbitrary) data of the given shape, dtype, and
        order.  Object arrays will be initialized to None.
    
    See Also
    --------
    empty_like : Return an empty array with shape and type of input.
    ones : Return a new array setting values to one.
    zeros : Ret

In [6]:
# Using "np.tile" function

arr_11 = np.tile([[8,9],[5,3]],3)
arr_11

array([[8, 9, 8, 9, 8, 9],
       [5, 3, 5, 3, 5, 3]])

In [2]:
import numpy as np
arr_12 = np.tile(np.array([[8,9],[5,3]]),3)
arr_12

array([[8, 9, 8, 9, 8, 9],
       [5, 3, 5, 3, 5, 3]])

# Numpy Datatypes

In [3]:
arr_1 = np.array([4,-2,5,9],dtype=float)
arr_1

array([ 4., -2.,  5.,  9.])

In [4]:
arr_1.dtype

dtype('float64')

In [5]:
arr_2 = np.array([4,-2,5,9])
print(arr_2)
arr_2.dtype

[ 4 -2  5  9]


dtype('int32')

In [7]:
arr_3 = np.array([2423435435,4635])
arr_3.dtype

dtype('int64')

In [6]:
arr_4 = np.array(['hello','hi','welcome'])
arr_4.dtype

dtype('<U7')

In [8]:
arr_5 = np.array([True,False])
print(arr_5.dtype)
arr_5

bool


array([ True, False])

# Typecasting

In [9]:
arr_6 = np.array([1,-3,5,7.45])
arr_6   #Default value of array in NUMPY is float

array([ 1.  , -3.  ,  5.  ,  7.45])

In [10]:
arr_1 = arr_1.astype(int)
print(arr_1.dtype)
arr_1

int32


array([ 4, -2,  5,  9])

# Numpy Indexing and slicing

In [11]:
arr_1 = np.arange(6)
arr_1

array([0, 1, 2, 3, 4, 5])

In [12]:
arr_1[0]

0

In [13]:
arr_1[0:2]

array([0, 1])

In [14]:
arr_1[-1]

5

In [15]:
arr_1[:-1]

array([0, 1, 2, 3, 4])

In [16]:
arr_1[::-1]

array([5, 4, 3, 2, 1, 0])

In [18]:
arr_2 = np.array([[4,3],[3,5],[1,2]])
arr_2

array([[4, 3],
       [3, 5],
       [1, 2]])

In [20]:
arr_2[2,1]

2

In [26]:
arr_2[2,1] = -3  #Assigning -3 to arr_2[2,1]
arr_2

array([[ 4,  3],
       [ 3,  5],
       [ 1, -3]])

In [27]:
# Retrieve the first row:

arr_2[1]

array([3, 5])

In [28]:
# Retrieve the 2nd row and all cols

arr_2[2,:]

array([ 1, -3])

In [29]:
# Retrieve the cols
# arr[row,col]

arr_2[:,1]

array([ 3,  5, -3])

In [31]:
arr_2[1:3,1]

array([ 5, -3])

In [32]:
arr_1

array([0, 1, 2, 3, 4, 5])

In [33]:
arr_1[6]

IndexError: index 6 is out of bounds for axis 0 with size 6

In [43]:
arr_3 = 2 * np.arange(10)
arr_3

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [36]:
arr_3[0:6:2]

array([0, 4, 8])

In [37]:
arr_3[:3]

array([0, 2, 4])

In [38]:
arr_3[3:]

array([ 6,  8, 10, 12, 14, 16, 18])

In [39]:
arr_3[::3]

array([ 0,  6, 12, 18])

In [41]:
arr_3[1] = -2
arr_3

array([ 0, -2,  4,  6,  8, 10, 12, 14, 16, 18])

In [42]:
arr_3[:3] = -2
arr_3

array([-2, -2, -2,  6,  8, 10, 12, 14, 16, 18])

In [44]:
arr_3[2:] = np.ones(8)
arr_3

array([0, 2, 1, 1, 1, 1, 1, 1, 1, 1])

In [45]:
## Creating 5x5 array

arr_4 = np.array([[1,2,3,4,5],[11,12,13,14,15],[21,22,23,24,25],[31,32,33,34,35],[41,42,43,44,45]])
arr_4

array([[ 1,  2,  3,  4,  5],
       [11, 12, 13, 14, 15],
       [21, 22, 23, 24, 25],
       [31, 32, 33, 34, 35],
       [41, 42, 43, 44, 45]])

In [46]:
arr_4[0,2:5]   #Extracting element in 0th row, 2nd and 3rd col

array([3, 4, 5])

In [47]:
arr_4[4:,4:]

array([[45]])

In [49]:
arr_4[::-1,::-1]  # 5x5 matrix is reversed

array([[45, 44, 43, 42, 41],
       [35, 34, 33, 32, 31],
       [25, 24, 23, 22, 21],
       [15, 14, 13, 12, 11],
       [ 5,  4,  3,  2,  1]])

In [50]:
arr_4[2::2,::2]

array([[21, 23, 25],
       [41, 43, 45]])

In [57]:
##
np.random.seed(2)
arr_1 = np.random.randint(25,50,5)
arr_1

array([33, 40, 38, 33, 47])

In [58]:
arr_even = (arr_1 %2 == 0)
arr_even

array([False,  True,  True, False, False])

In [59]:
arr_1[arr_even]

array([40, 38])

In [60]:
##

arr_country = np.array(['India','Russia','France','','Srilanka'])
arr_country

array(['India', 'Russia', 'France', '', 'Srilanka'], dtype='<U8')

In [61]:
arr_country[arr_country == ''] = 'Pakistan'
arr_country

array(['India', 'Russia', 'France', 'Pakistan', 'Srilanka'], dtype='<U8')

In [62]:
np.random.seed(2)
arr_1 = np.random.randint(25,50,10)
arr_1

array([33, 40, 38, 33, 47, 36, 43, 36, 33, 32])

In [63]:
arr_1[[1,3,8]]

array([40, 33, 33])

In [65]:
arr_1[[1,6]] = 100
arr_1

array([ 33, 100,  38,  33,  47,  36, 100,  36,  33,  32])

In [68]:
# Compex indexing

arr_14 = np.arange(20)
arr_14

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [69]:
arr_15 = np.arange(-11,-20,-1)[::-1]
arr_15

array([-19, -18, -17, -16, -15, -14, -13, -12, -11])

In [71]:
arr_14[:9] = arr_15
arr_14

array([-19, -18, -17, -16, -15, -14, -13, -12, -11,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19])

# View and Copy

In [1]:
import numpy as np

In [2]:
arr_1 = np.arange(5)
arr_1

array([0, 1, 2, 3, 4])

In [3]:
arr_2 = arr_1[::2]    # Even after modifing the element in the array, base array is modifited
arr_2

array([0, 2, 4])

In [4]:
arr_2[1] = -4      
arr_2

array([ 0, -4,  4])

In [6]:
arr_3 = np.arange(10)
arr_3

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [7]:
arr_4 = arr_3[:3].copy()    # Even after modifing the element in the array, base array is not modifited
arr_4

array([0, 1, 2])

In [8]:
arr_4[1] = -2   
arr_4

array([ 0, -2,  2])

In [9]:
arr_3

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

# Basic Operation

In [10]:
arr_1 = np.arange(1,10) * 4
arr_1

array([ 4,  8, 12, 16, 20, 24, 28, 32, 36])

In [11]:
arr_2 = np.arange(1,10) ** 4
arr_2

array([   1,   16,   81,  256,  625, 1296, 2401, 4096, 6561], dtype=int32)

In [12]:
arr_3 = arr_1 * 0.5
arr_3

array([ 2.,  4.,  6.,  8., 10., 12., 14., 16., 18.])

In [13]:
arr_4 = 3 + np.arange(0,20,2)
arr_4

array([ 3,  5,  7,  9, 11, 13, 15, 17, 19, 21])

In [15]:
arr_5 = np.arange(10)
arr_5[0]=10
arr_5

array([10,  1,  2,  3,  4,  5,  6,  7,  8,  9])

In [16]:
arr_6 = arr_4 - arr_5
arr_6

array([-7,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [18]:
arr_7 = arr_4 / arr_5
arr_7

array([0.3       , 5.        , 3.5       , 3.        , 2.75      ,
       2.6       , 2.5       , 2.42857143, 2.375     , 2.33333333])

In [20]:
arr_8 = arr_4 * arr_5
arr_8

array([ 30,   5,  14,  27,  44,  65,  90, 119, 152, 189])

In [21]:
arr_11 = np.arange(100)
%timeit arr_11 ** 3

2.19 µs ± 14.9 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)


In [23]:
arr_12 = range(100)
%timeit [arr_12[i] ** 3 for i in arr_12]

102 µs ± 157 ns per loop (mean ± std. dev. of 7 runs, 10000 loops each)


In [25]:
## Matrix multiplication

arr_21 = np.array([[5,2],[6,3]])
arr_22 = np.array([[2,3],[4,5]])
arr_23 = arr_21.dot(arr_22)
arr_23

array([[18, 25],
       [24, 33]])

In [26]:
##

arr_4

array([ 3,  5,  7,  9, 11, 13, 15, 17, 19, 21])

In [27]:
arr_5

array([10,  1,  2,  3,  4,  5,  6,  7,  8,  9])

In [29]:
arr_31 = arr_5 < arr_4
arr_31

array([False,  True,  True,  True,  True,  True,  True,  True,  True,
        True])

In [31]:
# Logical

arr_17 = np.array([True,False,True,False])
arr_18 = np.array([True,True,False,False])

arr_20 = np.logical_and(arr_17,arr_18)
arr_20

array([ True, False, False, False])

In [32]:
arr_21 = np.logical_or(arr_17,arr_18)
arr_21

array([ True,  True,  True, False])

In [33]:
arr_13 = np.array([np.pi,np.pi/2])
print(arr_13)

arr_25 = np.sin(arr_13)
arr_25

[3.14159265 1.57079633]


array([1.2246468e-16, 1.0000000e+00])

In [34]:
arr_1 = np.arange(1,6)
arr_2 = np.arange(1,8)
arr_3 = arr_1 + arr_2

ValueError: operands could not be broadcast together with shapes (5,) (7,) 

In [38]:
arr_11 = np.arange(1,7)
arr_12 = np.array([1,2,3,4,5,6])
arr_13 = np.array_equal(arr_11, arr_12)
arr_13

True

# Broadcasting

In [40]:
arr_1 = np.ones([5,2])
arr_1

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [41]:
arr_2 = np.array([5,2])
arr_2

array([5, 2])

In [42]:
arr_3 = arr_1 + arr_2
arr_3

array([[6., 3.],
       [6., 3.],
       [6., 3.],
       [6., 3.],
       [6., 3.]])

In [43]:
arr_4 = np.array([[11,22,33]])
arr_5 = arr_4.T
arr_5

array([[11],
       [22],
       [33]])

In [44]:
arr_6 = arr_4 + arr_5
arr_6

array([[22, 33, 44],
       [33, 44, 55],
       [44, 55, 66]])