# Array manipulation & sorting

In [3]:
import numpy as np

In [4]:
arr_1 = np.array([[1,2,3,4],[3,4,5,6],[5,6,7,8],[7,8,9,10]])
arr_1

array([[ 1,  2,  3,  4],
       [ 3,  4,  5,  6],
       [ 5,  6,  7,  8],
       [ 7,  8,  9, 10]])

In [6]:
arr_2 = np.array([[11],[12],[13],[14]])
arr_2

array([[11],
       [12],
       [13],
       [14]])

In [7]:
arr_3 = arr_1 + arr_2
arr_3

array([[12, 13, 14, 15],
       [15, 16, 17, 18],
       [18, 19, 20, 21],
       [21, 22, 23, 24]])

In [18]:
## Array shape Manipulation

arr = np.arange(20)

arr_4 = arr.reshape(2,10) 
arr_4

# if element in the "arr" is less than or greater than the place in array "arr_4",
# then it thrown a error

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19]])

In [20]:
arr_5 = np.arange(10,15)

arr_5.resize(2,4)
arr_5

# if element in the "arr" is less than or greater than the place in array "arr_4",
# then it append zero

array([[10, 11, 12, 13],
       [14,  0,  0,  0]])

In [21]:
arr_6 = np.arange(10,15)
arr_7 = arr_6
arr_7.resize(2,2)

ValueError: cannot resize an array that references or is referenced
by another array in this way.  Use the resize function

In [24]:
arr_6 = np.arange(10,15)
arr_7 = arr_6.copy()
arr_7.resize(2,2)
arr_7

array([[10, 11],
       [12, 13]])

In [27]:
arr_8 = np.arange(10,15)

arr_9 = np.resize(arr_8,(8,))
arr_9

array([10, 11, 12, 13, 14, 10, 11, 12])

In [4]:
## np.ravel()

arr_10 = np.array([np.arange(2,7),np.arange(15,20)])
arr_10

arr_11 = arr_10.ravel()  # multiple multi-dimension array is converted to single dimension array
arr_11

array([ 2,  3,  4,  5,  6, 15, 16, 17, 18, 19])

In [5]:
## np.flatten()

arr_12 = arr_10.flatten()  # same operation of "ravel()"
arr_12

array([ 2,  3,  4,  5,  6, 15, 16, 17, 18, 19])

In [31]:
## np.shape

arr_13 = np.array([21,22,23])
arr_13.shape   # given the dimension of an array

(3,)

In [32]:
## np.newaxis

arr_14 = arr_13[:,np.newaxis]
print(arr_14.shape)  # adding new dimension
arr_14   ### ---> 2D array

(3, 1)


array([[21],
       [22],
       [23]])

In [36]:
arr_15 = arr_14[:,np.newaxis]
print(arr_15.shape)
arr_15  ### ---> 3D array

(3, 1, 1)


array([[[21]],

       [[22]],

       [[23]]])

# Array sorting

In [37]:
arr_16 = np.array([[4,5,2],[3,2,1]])
arr_16.sort(axis = 0)  ## sort the matrix by col
arr_16

array([[3, 2, 1],
       [4, 5, 2]])

In [38]:
arr_17 = np.array([[4,5,2],[3,2,1]])
arr_17.sort(axis = 1)  ## sort the matrix by row
arr_17

array([[2, 4, 5],
       [1, 2, 3]])

In [39]:
?np.sort

In [40]:
## Reduction & statistical operations

arr_3 = np.arange(2,6)
arr_3.prod()  # given the product of all the elements inside the array

120

In [41]:
arr_16 = np.array([[4,5,2],[3,2,1]])
arr_18 = np.prod(arr_16, axis = 0)
arr_18

array([12, 10,  2])

In [42]:
arr_16 = np.array([[4,5,2],[3,2,1]])
arr_19 = np.prod(arr_16, axis = 1)
arr_19

array([40,  6])